### ISSUE TITLE
TypeScript 2.9 breaks schema generation

### ISSUE THREAD

**Issue by 5ebastianMeier** [essential-projects/typescript-json-schema#2]
When using TypeScript 2.9, the schema generation encounters an error.

This error appears when an interface is extending from another TypeScript Symbol (most likely also an interface).

I've looked into the source code referenced in the stack trace and it seems that the issue is only present in js doc reflection methods that we currently don't use when we generate schemas.

Currently the last working TypeScript version seems to be `2.8.3`.

```
/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:106678
            var superType = typeChecker.getTypeAtLocation(superTypeNode);
                                        ^

TypeError: Cannot read property 'getTypeAtLocation' of undefined
    at /Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:106678:41
    at Object.firstDefined (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:1807:26)
    at findInheritedJSDocComments (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:106673:19)
    at getDocumentationComment (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:106656:37)
    at SymbolObject.getDocumentationComment (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript/lib/typescript.js:106505:45)
    at JsonSchemaGenerator.parseCommentsIntoDefinition (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript-json-schema/typescript-json-schema.js:112:31)
    at JsonSchemaGenerator.getTypeDefinition (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript-json-schema/typescript-json-schema.js:730:18)
    at JsonSchemaGenerator.getDefinitionForProperty (/Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript-json-schema/typescript-json-schema.js:232:31)
    at /Users/seb/_dev/Contrib/ProcessEngine/process_engine_meta/node_modules/typescript-json-schema/typescript-json-schema.js:583:37
    at Array.reduce (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @process-engine/process_engine_contracts@8.0.0 build-schemas: `gulp typescript-schema`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @process-engine/process_engine_contracts@8.0.0 build-schemas script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seb/.npm/_logs/2018-06-04T09_37_41_849Z-debug.log
```

**Comment by 5ebastianMeier** [comment]
I was able to verify that `typescript@2.8.3` indeed is the last working version.

For a quick fix we would need to fork `ts-node` as this is a dependency of `typescript-json-schema` and declares a dependency on `typescript@^2.8.3` itself, which causes `typescript@2.9` to be installed.

In the fork we need to specify the dependency explicitly to be `typescript@2.8.3`.

The real fix needs to happen in the implementation of this package, but I don't think we need features exclusive to typescript >=2.9 to generate schemas anyway.

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72
